
ensure_tpm_hide_cmdline() {
  # $1 = text file with linux cmdline (grub.cfg / usb.A.cfg / kern cfg)
  local f="$1"
  [ -f "$f" ] || return 0
  if ! grep -q 'tpm_tis.force=0' "$f"; then
    sed -i 's/console= /console= tpm_tis.force=0 /g' "$f" || true
  fi
  if ! grep -q 'modprobe.blacklist=tpm_tis,tpm_crb' "$f"; then
    sed -i 's/tpm_tis.force=0/tpm_tis.force=0 modprobe.blacklist=tpm_tis,tpm_crb/' "$f" || true
  fi
}
#!/usr/bin/env bash
# build-fydeos-starlite.sh — turn a FydeOS or OpenFyde iris image into a
# StarLite image that boots verified, keeps Android/WiFi, carries every StarLite
# hardware fix, AND installs from the on-screen GUI button.
#
# The image's own /etc/lsb-release and /lib/modules decide the product and the
# kernel. The accelerometer module is chosen for that kernel. The kernel in
# the image is not replaced.
#
#   ./scripts/build-fydeos-starlite.sh [--lean|--no-lean] [--identify] <image.bin> [output.bin]
#
# Defaults: --lean ON (strip Fyde AI/extras; keep Files, ARC/fyDroid, Crostini, player).
# Escape hatch: --no-lean
#
# Proven 2026-08-07 on FydeOS iris R144 (16503.20.22.24): GUI install, Wi-Fi,
# tablet mode and Android all confirmed working on-device.
#
# Latest StarLite fixes injected from out/release/sources/ (as of 2026-09-20):
#   - mxc4005.ko (per-KVER: detect /lib/modules/*; refuse wrong vermagic) +
#       load-mxc4005.conf + starlite-mxc4005.conf + 61-starlite-accel.hwdb
#   - edp-resume-fix.sh  (remember last brightness via /var/lib/starlite-last-brightness)
#   - lid-touch-guard.sh  (unbind Goodix when lid closed; honors external-only flag)
#   - external-only-guard.sh  (force eDP off + unbind touch when user disables
#       internal display while HDMI/USB-C connected — case without keyboard)
#   - tablet-switch, power-sleep, install-to-internal
#   - i915.enable_dpcd_backlight=0 baked into grub/kernel cmdline (verity re-seal)
#   - optional lean_strip_fyde_extras (see docs/LEAN-STARLITE.md)
#
# ---------------------------------------------------------------------------
# WHY THE GUI INSTALL BREAKS IF YOU SKIP THE RE-SEAL  (the bug that cost weeks)
#
# The verity root digest lives in FOUR places. Modifying ROOT-A changes its real
# hash, and every copy must be updated or the install dies:
#
#   1. ROOT-A's own hashtree            (regenerated by the re-seal)
#   2. /efi/boot/grub.cfg   on the ESP  <- the ONLY one updated originally
#   3. KERN-A *and* KERN-B vboot config <- MISSED -> cros_installer aborts
#   4. /syslinux/usb.A.cfg  on the ESP  <- MISSED
#
# cros_installer reads the digest out of the KERNEL config to extract the verity
# arguments. Stale digest -> hard fail -> postinst aborts. And chromeos-postinst
# DISCARDS cros_installer's exit status, so the GUI can report success on a disk
# that never got installed. That silent failure is why this took so long to find.
#
# BOTH kernel slots must be patched: the installed KERN-A is copied from the
# SOURCE KERN-B, so fixing only partition 2 leaves the install broken.
#
# Do NOT touch grub's "verified image B" entry: it references ROOT-B's own
# PARTUUID, and ROOT-B is never modified, so its stock digest is CORRECT there.
# Patching it breaks the B slot.
#
# Myth, now disproven: chromeos-install does NOT rebuild a pristine rootfs. It
# block-copies ROOT-A with dd. The GUI installer was never the villain.
# ---------------------------------------------------------------------------
set -uo pipefail

BASE="$(cd "$(dirname "$0")/.." && pwd)"
SRCDIR="$BASE/out/release/sources"
TOOLS="$BASE/crostini/tools"
DEVKEYS="$BASE/vboot/devkeys"

# shellcheck source=lib-starlite-mxc.sh
source "$(dirname "$0")/lib-starlite-mxc.sh"

LEAN=1
SKIP_MXC=0
IDENTIFY=0
ARGS=()
for a in "$@"; do
  case "$a" in
    --lean) LEAN=1 ;;
    --no-lean) LEAN=0 ;;
    --skip-mxc) SKIP_MXC=1 ;;
    --identify) IDENTIFY=1 ;;
    -h|--help)
      sed -n '2,25p' "$0"; exit 0 ;;
    *) ARGS+=("$a") ;;
  esac
done
set -- "${ARGS[@]}"

IN="${1:?usage: $0 [--lean|--no-lean] [--skip-mxc] [--identify] <fydeos-or-openfyde.bin> [output.bin]}"
OUT="${2:-$BASE/out/FydeOS-StarLite-$(basename "${IN%.bin}")-fixed.bin}"

say(){ printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
ok(){  printf '  \033[32m✓\033[0m %s\n' "$*"; }
die(){ printf '  \033[31m✗ %s\033[0m\n' "$*"; exit 1; }

[ -e "$IN" ] || die "missing: $IN"
if [ "$IDENTIFY" = 1 ]; then
  starlite_print_identity "$IN"
  exit 0
fi

W="$BASE/vk1-verify/rebuild"; rm -rf "$W"; mkdir -p "$W"

for f in "$TOOLS/run_verity.sh" "$TOOLS/run_futility.sh" "$DEVKEYS/kernel.keyblock"; do
  [ -e "$f" ] || die "missing: $f"
done

REQUIRED_SOURCES=(
  power-sleep power-sleep.sh edp-resume-fix.sh tablet-switch lid-touch-guard.sh
  external-only-guard.sh install-to-internal
  power-sleep.conf edp-resume.conf tablet-switch.conf lid-touch-guard.conf
  external-only-guard.conf load-mxc4005.conf 61-starlite-accel.hwdb 61-starlite-accel.rules
  starlite-mxc4005.conf
  starlite-bt-bluez.conf wifi-resume-fix.sh wifi-resume.conf elastos-wifi-heal
  trunksd.conf tpm2-simulator.conf hwsec-coherence-guard.conf
)
# mxc4005.ko is resolved per-KVER after we detect the image kernel (may live under
# sources/mxc4005/$KVER/ or flat sources/mxc4005.ko).
for f in "${REQUIRED_SOURCES[@]}"; do
  [ -e "$SRCDIR/$f" ] || die "missing source fix: $SRCDIR/$f"
done
ok "all StarLite fix sources present in $SRCDIR (mxc .ko selected after KVER detect)"

# Sanity-check the staged scripts still carry the latest behaviors.
grep -q starlite-last-brightness "$SRCDIR/edp-resume-fix.sh" \
  || die "edp-resume-fix.sh missing starlite-last-brightness (brightness-remember)"
grep -q SuspendDone "$SRCDIR/edp-resume-fix.sh" \
  || die "edp-resume-fix.sh must relight only on SuspendDone"
grep -q 'date +%s' "$SRCDIR/edp-resume-fix.sh" \
  && die "edp-resume-fix.sh still blanks the panel on a clock step" || true
grep -q 'modprobe -r' "$SRCDIR/wifi-resume-fix.sh" \
  && die "wifi-resume-fix.sh still unloads iwlwifi" || true
grep -q 'exec trunksd --simulator' "$SRCDIR/trunksd.conf" \
  && die "trunksd.conf still starts a second TPM" || true
# TPM hide must survive lean re-seal when the input image already has it
# (v6.13.23+). Inject if missing so cryptohome keeps one software TPM.
# See docs/HANDOFF.md Cryptohome — hold.
grep -q starlite-external-only "$SRCDIR/external-only-guard.sh" \
  || die "external-only-guard.sh missing /run/starlite-external-only flag"
grep -q starlite-external-only "$SRCDIR/lid-touch-guard.sh" \
  || die "lid-touch-guard.sh missing external-only coordination"
grep -q mxc4005 "$SRCDIR/load-mxc4005.conf" \
  || die "load-mxc4005.conf missing mxc4005"
grep -q starlite-iio-setup "$SRCDIR/load-mxc4005.conf" \
  && die "load-mxc4005.conf must not call a userspace sensor script" || true
grep -q 'insmod' "$SRCDIR/load-mxc4005.conf" \
  && die "load-mxc4005.conf must not insmod a second mxc4005" || true
grep -q 'printf "%s" bluez' "$SRCDIR/starlite-bt-bluez.conf" \
  || die "starlite-bt-bluez.conf must select BlueZ"
grep -q 'acpi:MXC6655:MXC6655::dmi:' "$SRCDIR/61-starlite-accel.hwdb" \
  || die "hwdb missing the double-colon MXC6655 key"
grep -q 'ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1' "$SRCDIR/61-starlite-accel.hwdb" \
  || die "hwdb missing the proven mount matrix"
grep -q 'start on never' "$SRCDIR/hwsec-coherence-guard.conf" \
  || die "hwsec-coherence-guard.conf must stay retired"
grep -E -q '^start on ' "$SRCDIR/tpm2-simulator.conf" \
  && die "tpm2-simulator.conf must not start itself" || true
PREINIT="$BASE/scripts/v6.13.3-payload/check_tpm_preinit_condition"
[ -f "$PREINIT" ] || die "missing $PREINIT"
grep -q 'exit 0' "$PREINIT" || die "check_tpm_preinit_condition must exit 0"
grep -v '^[[:space:]]*#' "$PREINIT" | grep -q no_preinit \
  && die "check_tpm_preinit_condition must not touch no_preinit" || true
grep -q 'modprobe -r' "$SRCDIR/elastos-wifi-heal" \
  && die "elastos-wifi-heal still unloads iwlwifi" || true
ok "source scripts match expected latest behaviors"
ok "lean mode: $LEAN"

# ---------------------------------------------------------------------------
# lean_strip_fyde_extras — careful, reversible-in-spirit strip of Fyde extras.
# KEEP: ARC/fyDroid, Crostini/termina, Files/Gallery/Player, SELinux, verity,
#       fyde_rhythm IME, hwtuner-script.
# See docs/LEAN-STARLITE.md.
# ---------------------------------------------------------------------------

# Bake accelerometer hwdb into hwdb.bin (loose .hwdb files are ignored until compiled)
starlite_refresh_hwdb() {
  local img="$1"
  local u="$W/udev-root"
  rm -rf "$u"
  mkdir -p "$u/etc/udev"
  guestfish --ro -a "$img" -m /dev/sda3:/ <<GF 2>/dev/null || die "could not read image hwdb"
download /etc/udev/hwdb.bin $u/etc/udev/hwdb.bin
copy-out /etc/udev/hwdb.d $u/etc/udev
GF
  # Host compiles hwdb with our StarLite entries
  if command -v systemd-hwdb >/dev/null; then
    systemd-hwdb --root="$u" update 2>/dev/null || systemd-hwdb update --root="$u" 2>/dev/null || true
  elif command -v udevadm >/dev/null; then
    udevadm hwdb --update --root="$u" 2>/dev/null || true
  fi
  if [ -s "$u/etc/udev/hwdb.bin" ]; then
    guestfish --rw -a "$img" -m /dev/sda3:/ \
      upload "$u/etc/udev/hwdb.bin" /etc/udev/hwdb.bin 2>/dev/null || true
    if strings "$u/etc/udev/hwdb.bin" | grep -F -q 'MXC6655:MXC6655::'; then
      ok "hwdb.bin contains the double-colon MXC6655 key"
    else
      die "hwdb.bin is missing acpi:MXC6655:MXC6655:: — rotation would not bind"
    fi
  else
    die "hwdb.bin was not produced"
  fi
}

lean_strip_fyde_extras() {
  local img="$1"
  say "lean) strip Fyde AI/extras (keep ARC + Crostini + Files + Player)"

  # Host-side staging for small policy / edited files we upload back
  local L="$W/lean"; mkdir -p "$L"

  # 1) Pull files we may edit
  guestfish --ro -a "$img" -m /dev/sda3:/ <<GF 2>/dev/null || true
download /etc/fydeos_scripts/list $L/fydeos_scripts.list
download /etc/chrome_dev.conf $L/chrome_dev.conf
GF

  # 2) Edit fydeos_scripts list: drop ota-checker + backup; keep hwtuner
  if [ -s "$L/fydeos_scripts.list" ]; then
    grep -vE '^(fydeos-ota-checker|fydeos-backup)$' "$L/fydeos_scripts.list" > "$L/fydeos_scripts.list.new" || true
    mv "$L/fydeos_scripts.list.new" "$L/fydeos_scripts.list"
    ok "fydeos_scripts/list: removed ota-checker + backup (kept hwtuner if present)"
  fi

  # 3) chrome_dev.conf: drop fyde-auto-signin-delay; keep ARC flags
  if [ -s "$L/chrome_dev.conf" ]; then
    sed -E 's/(^|[[:space:]])--fyde-auto-signin-delay=[^[:space:]]+//g' "$L/chrome_dev.conf" \
      | sed 's/  */ /g' > "$L/chrome_dev.conf.new"
    mv "$L/chrome_dev.conf.new" "$L/chrome_dev.conf"
    ok "chrome_dev.conf: removed --fyde-auto-signin-delay=* (ARC flags preserved)"
  fi

  # 4) Block Fyde account apps only.
  # Keep Gallery, Files, Camera, and the RIME input method.
  # Gallery is the Chrome system media app, not one of these ids.
  mkdir -p "$L/policies"
  cat > "$L/policies/starlite_lean_extensions.json" <<'JSON'
{
  "ExtensionInstallBlocklist": [
    "fogdcaodknbhigpklbhepedofamkfbln",
    "hidnajblbifdkmheebalalchohohmaef",
    "mofiofjpikncjaigmdlblhojbnkabako"
  ],
  "URLBlocklist": [
    "https://notes.fydeos.io/*",
    "https://ai.fydeos.io/*",
    "chrome://fydeos-ai/*",
    "https://rdp.fydeos.io/*"
  ],
  "WebAppSettings": [
    {
      "manifest_id": "https://notes.fydeos.io/",
      "installation_mode": "blocked"
    },
    {
      "manifest_id": "https://notes.fydeos.io/?source=pwa",
      "installation_mode": "blocked"
    },
    {
      "manifest_id": "https://ai.fydeos.io/",
      "installation_mode": "blocked"
    },
    {
      "manifest_id": "https://ai.fydeos.io/chat/",
      "installation_mode": "blocked"
    }
  ]
}
JSON
  if grep -E -q 'media-app|file-manager|camera-app' "$L/policies/starlite_lean_extensions.json"; then
    die "lean policy would block Gallery, Files, or Camera"
  fi

  # 5) Apply removals + uploads inside ROOT-A
  guestfish --rw -a "$img" -m /dev/sda3:/ <<GF 2>&1 | grep -v '^$' | sed 's/^/    /'
# Default Fyde CRX validation + matching crx (do not remove empty parent dirs)
glob rm-f /usr/share/import_extensions/fogdcaodknbhigpklbhepedofamkfbln-*.crx
glob rm-f /usr/share/import_extensions/mofiofjpikncjaigmdlblhojbnkabako-*.crx
glob rm-f /usr/share/import_extensions/validation/fogdcaodknbhigpklbhepedofamkfbln*
glob rm-f /usr/share/import_extensions/validation/mofiofjpikncjaigmdlblhojbnkabako*
glob rm-f /usr/share/import_extensions/hidnajblbifdkmheebalalchohohmaef-*.crx
glob rm-f /usr/share/import_extensions/validation/hidnajblbifdkmheebalalchohohmaef*

# Force-installed Fyde account apps: App Store, System Controller, Remote Desktop.
# The RIME input method (nfglebjgiflmmcdddkbcbgmdkomlfcpa) stays.
rm-f /usr/share/chromium/extensions/fogdcaodknbhigpklbhepedofamkfbln.json
rm-f /usr/share/chromium/extensions/hidnajblbifdkmheebalalchohohmaef.json
rm-f /usr/share/chromium/extensions/mofiofjpikncjaigmdlblhojbnkabako.json

# Optional Fyde remote helpers
rm-rf /usr/share/remote-help
rm-rf /usr/share/novnc

# Optional OTA / backup content (keep dirs if present by emptying via rm-rf of known trees)
rm-rf /usr/share/fydeos-ota-checker
rm-rf /usr/share/fydeos-backup

# Upload edited lists / conf if we staged them
GF

  # Drop Fyde account CRXs from the import list. Keep the RIME IME and Everdroid lines.
guestfish --ro -a "$img" -m /dev/sda3:/ \
  download /usr/share/import_extensions/validation/fydeos-default-apps-1.0.0.validation \
  "$L/fydeos-default-apps.validation" 2>/dev/null || true
if [ -s "$L/fydeos-default-apps.validation" ]; then
  grep -vE 'fogdcaodknbhigpklbhepedofamkfbln|hidnajblbifdkmheebalalchohohmaef|mofiofjpikncjaigmdlblhojbnkabako' \
    "$L/fydeos-default-apps.validation" > "$L/fydeos-default-apps.validation.new" || true
  mv "$L/fydeos-default-apps.validation.new" "$L/fydeos-default-apps.validation"
  guestfish --rw -a "$img" -m /dev/sda3:/ \
    upload "$L/fydeos-default-apps.validation" \
    /usr/share/import_extensions/validation/fydeos-default-apps-1.0.0.validation \
    2>/dev/null || true
  ok "default-apps list no longer imports Store, System Controller, or Remote Desktop"
fi

# Upload edited files only if we have them (separate guestfish for clarity)
  if [ -s "$L/fydeos_scripts.list" ]; then
    guestfish --rw -a "$img" -m /dev/sda3:/ <<GF 2>/dev/null
mkdir-p /etc/fydeos_scripts
upload $L/fydeos_scripts.list /etc/fydeos_scripts/list
GF
  fi
  if [ -s "$L/chrome_dev.conf" ]; then
    guestfish --rw -a "$img" -m /dev/sda3:/ \
      upload "$L/chrome_dev.conf" /etc/chrome_dev.conf 2>/dev/null || true
  fi
  guestfish --rw -a "$img" -m /dev/sda3:/ <<GF 2>/dev/null
mkdir-p /etc/opt/chrome/policies/managed
upload $L/policies/starlite_lean_extensions.json /etc/opt/chrome/policies/managed/starlite_lean_extensions.json
GF

  ok "lean strip applied (ARC/Crostini/Files untouched)"
}

say "1) copy base image"
cp --reflink=auto "$IN" "$OUT" || die "copy failed"
ok "$OUT"

say "2) partition geometry + detect image KVER"
ROOTA_START=$(sgdisk -i 3 "$OUT" | grep -o 'First sector: [0-9]*' | awk '{print $3}')
KA_START=$(sgdisk -i 2 "$OUT" | grep -o 'First sector: [0-9]*' | awk '{print $3}')
KA_SIZE=$(sgdisk -i 2 "$OUT" | grep -oE 'Partition size: [0-9]*' | awk '{print $3}')
KB_START=$(sgdisk -i 4 "$OUT" | grep -o 'First sector: [0-9]*' | awk '{print $3}')
KB_SIZE=$(sgdisk -i 4 "$OUT" | grep -oE 'Partition size: [0-9]*' | awk '{print $3}')
ROOTA_OFF=$((ROOTA_START * 512))
# ROOT-A payload size comes from the grub dm= line: "0 <sectors> verity ..."
guestfish --ro -a "$OUT" -m /dev/sda12:/ download /efi/boot/grub.cfg "$W/grub.cfg" 2>/dev/null || die "no grub.cfg"
PAY_SECTORS=$(grep -o 'ro 1,0 [0-9]*' "$W/grub.cfg" | head -1 | awk '{print $3}')
PAY_BLOCKS=$((PAY_SECTORS / 8))
PAY_BYTES=$((PAY_SECTORS * 512))
SALT=$(grep -o 'salt=[0-9a-f]*' "$W/grub.cfg" | head -1 | cut -d= -f2)
OLD=$(grep -o 'root_hexdigest=[0-9a-f]*' "$W/grub.cfg" | head -1 | cut -d= -f2)
ok "ROOT-A @sector $ROOTA_START  payload ${PAY_BLOCKS}x4K  salt ${SALT:0:16}…"
ok "current grub digest ${OLD:0:16}…"

starlite_print_identity "$OUT"
KVER=$IMAGE_KVER
ok "image KVER=$KVER ($IMAGE_FAMILY)"
export STARLITE_SKIP_MXC=$SKIP_MXC
# Do not compile a module here. A wrong kernel tree would not load, and
# replacing vmlinuz is not allowed. The cache must already match this KVER.
starlite_select_mxc_ko "$KVER"
MXC_SKIP=${MXC_SKIP:-0}
if [ "${MXC_SKIP:-0}" != 1 ]; then
  starlite_check_trigger_name "$IMAGE_FAMILY" "$MXC_KO"
fi

# MXC_KO + MXC_VERMAGIC now set

say "3) PROOF-OF-METHOD — reproduce the EXISTING digest before trusting anything"
# ChromeOS uses dm-bht, NOT upstream dm-verity: veritysetup gives the WRONG digest.
dd if="$OUT" of="$W/roota.img" bs=512 skip="$ROOTA_START" count="$PAY_SECTORS" status=none
GOT=$("$TOOLS/run_verity.sh" mode=create alg=sha256 payload="$W/roota.img" \
      payload_blocks="$PAY_BLOCKS" hashtree="$W/h0.img" salt="$SALT" 2>/dev/null \
      | grep -o 'root_hexdigest=[0-9a-f]*' | cut -d= -f2)
HASHSTART=$(grep -o 'hashstart=[0-9]*' "$W/grub.cfg" | head -1 | cut -d= -f2)
ROOTA_SECTORS=$(sgdisk -i 3 "$OUT" | grep -oE 'Partition size: [0-9]*' | awk '{print $3}')
if [ "$GOT" = "$OLD" ]; then
  ok "reproduced $GOT — method trusted"
elif [ -n "$GOT" ] && [ "$HASHSTART" = "$PAY_SECTORS" ] && [ "${#SALT}" -eq 64 ] \
     && [ "${#GOT}" -eq 64 ] && [ "$PAY_SECTORS" -lt "$ROOTA_SECTORS" ]; then
  # Stock OpenFyde ships a digest that is not the hash of ROOT-A. The image
  # still boots because dm_verity.error_behavior=3. The size and salt above
  # are the values the bootloader will use, so the re-seal publishes the
  # digest of the bytes we ship. OLD stays the published string so it can be
  # replaced in grub and both kernel slots.
  echo "  WARN: published digest ${OLD:0:16}… is not the hash of this ROOT-A (${GOT:0:16}…)."
  echo "        Boot-line size and salt check out. The re-seal will publish the real digest."
else
  die "PROOF FAILED: recomputed $GOT != grub's $OLD — parameters wrong, ABORT"
fi

say "4) inject StarLite fixes into ROOT-A (KVER=$KVER)"
# ChromeOS ext2 RO-compat marker must be cleared or guestfish --rw fails "bad superblock"
printf '\x00' | dd of="$OUT" bs=1 seek=$((ROOTA_OFF + 0x467)) count=1 conv=notrunc status=none
ok "cleared ext2 RO marker"

# Host-side modules.dep snippet (appended if depmod unavailable in guest)
MXC_REL="kernel/drivers/iio/accel/mxc4005.ko"
printf '%s:\n' "$MXC_REL" > "$W/mxc4005.modules.dep.line"

if [ "${MXC_SKIP:-0}" != "1" ]; then
  guestfish --rw -a "$OUT" -m /dev/sda3:/ <<GFMXC 2>&1 | grep -v '^$' | sed 's/^/    /'
mkdir-p /lib/modules/$KVER/kernel/drivers/iio/accel
upload $MXC_KO /lib/modules/$KVER/kernel/drivers/iio/accel/mxc4005.ko
chmod 0644 /lib/modules/$KVER/kernel/drivers/iio/accel/mxc4005.ko
GFMXC
  ok "uploaded mxc4005.ko for $KVER"
else
  ok "skipped mxc4005.ko upload (--skip-mxc)"
fi

guestfish --rw -a "$OUT" -m /dev/sda3:/ <<GF 2>&1 | grep -v '^$' | sed 's/^/    /'
upload $SRCDIR/power-sleep /usr/sbin/power-sleep
upload $SRCDIR/power-sleep.sh /usr/sbin/power-sleep.sh
upload $SRCDIR/edp-resume-fix.sh /usr/sbin/edp-resume-fix.sh
upload $SRCDIR/tablet-switch /usr/sbin/tablet-switch
upload $SRCDIR/lid-touch-guard.sh /usr/sbin/lid-touch-guard.sh
upload $SRCDIR/external-only-guard.sh /usr/sbin/external-only-guard.sh
upload $SRCDIR/install-to-internal /usr/sbin/install-to-internal
upload $SRCDIR/power-sleep.conf /etc/init/power-sleep.conf
upload $SRCDIR/edp-resume.conf /etc/init/edp-resume.conf
upload $SRCDIR/tablet-switch.conf /etc/init/tablet-switch.conf
upload $SRCDIR/lid-touch-guard.conf /etc/init/lid-touch-guard.conf
upload $SRCDIR/external-only-guard.conf /etc/init/external-only-guard.conf
upload $SRCDIR/load-mxc4005.conf /etc/init/load-mxc4005.conf
mkdir-p /lib/modules/$KVER/kernel/drivers/iio/accel
mkdir-p /etc/udev/hwdb.d
upload $SRCDIR/61-starlite-accel.hwdb /etc/udev/hwdb.d/61-starlite-accel.hwdb
upload $SRCDIR/61-starlite-accel.rules /etc/udev/rules.d/61-starlite-accel.rules
mkdir-p /etc/modules-load.d
upload $SRCDIR/starlite-mxc4005.conf /etc/modules-load.d/starlite-mxc4005.conf
mkdir-p /usr/local/sbin
upload $SRCDIR/starlite-bt-bluez.conf /etc/init/starlite-bt-bluez.conf
chmod 0644 /etc/init/starlite-bt-bluez.conf
upload $SRCDIR/wifi-resume-fix.sh /usr/sbin/wifi-resume-fix.sh
chmod 0755 /usr/sbin/wifi-resume-fix.sh
upload $SRCDIR/wifi-resume.conf /etc/init/wifi-resume.conf
chmod 0644 /etc/init/wifi-resume.conf
upload $SRCDIR/elastos-wifi-heal /usr/sbin/elastos-wifi-heal
chmod 0755 /usr/sbin/elastos-wifi-heal
upload $SRCDIR/trunksd.conf /etc/init/trunksd.conf
chmod 0644 /etc/init/trunksd.conf
upload $SRCDIR/tpm2-simulator.conf /etc/init/tpm2-simulator.conf
chmod 0644 /etc/init/tpm2-simulator.conf
upload $SRCDIR/hwsec-coherence-guard.conf /etc/init/hwsec-coherence-guard.conf
chmod 0644 /etc/init/hwsec-coherence-guard.conf
upload $PREINIT /usr/sbin/check_tpm_preinit_condition
chmod 0755 /usr/sbin/check_tpm_preinit_condition
chmod 0755 /usr/sbin/power-sleep
chmod 0755 /usr/sbin/power-sleep.sh
chmod 0755 /usr/sbin/edp-resume-fix.sh
chmod 0755 /usr/sbin/tablet-switch
chmod 0755 /usr/sbin/lid-touch-guard.sh
chmod 0755 /usr/sbin/external-only-guard.sh
chmod 0755 /usr/sbin/install-to-internal
GF

# depmod if the guest has it; else append modules.dep line
guestfish --rw -a "$OUT" -m /dev/sda3:/ <<GF 2>/dev/null || true
sh 'command -v depmod >/dev/null && depmod -a $KVER || true'
GF
# Always ensure modules.dep mentions mxc4005 (idempotent append) — unless skipped
if [ "${MXC_SKIP:-0}" != "1" ]; then
  guestfish --ro -a "$OUT" -m /dev/sda3:/ \
    download "/lib/modules/$KVER/modules.dep" "$W/modules.dep" 2>/dev/null || true
  if [ -f "$W/modules.dep" ]; then
    if ! grep -q 'kernel/drivers/iio/accel/mxc4005\.ko' "$W/modules.dep"; then
      printf '%s:\n' "$MXC_REL" >> "$W/modules.dep"
      guestfish --rw -a "$OUT" -m /dev/sda3:/ \
        upload "$W/modules.dep" "/lib/modules/$KVER/modules.dep" 2>/dev/null || true
      ok "appended mxc4005 to modules.dep"
    else
      ok "modules.dep already lists mxc4005"
    fi
  fi
fi

# powerd prefs: no ALS on this panel, and use the lid
for p in use_lid:1 has_ambient_light_sensor:0 \
         legacy_power_button:0 \
         internal_backlight_no_als_ac_brightness:80 \
         internal_backlight_no_als_battery_brightness:80; do
  printf '%s\n' "${p#*:}" > "$W/pref"
  guestfish --rw -a "$OUT" -m /dev/sda3:/ upload "$W/pref" \
     "/usr/share/power_manager/board_specific/${p%%:*}" 2>/dev/null
done
# GI-3: the grub TEMPLATE inside ROOT-A must carry the brightness param, or a
# successful GUI install silently drops it on the installed system.
if guestfish --ro -a "$OUT" -m /dev/sda3:/ exists /boot/efi/boot/grub.cfg 2>/dev/null | grep -q true; then
  guestfish --rw -a "$OUT" -m /dev/sda3:/ download /boot/efi/boot/grub.cfg "$W/tmpl.cfg" 2>/dev/null
  grep -q 'i915.enable_dpcd_backlight=0' "$W/tmpl.cfg" || \
    sed -i 's/i915.enable_psr=0/i915.enable_psr=0 i915.enable_dpcd_backlight=0/g' "$W/tmpl.cfg"
  guestfish --rw -a "$OUT" -m /dev/sda3:/ upload "$W/tmpl.cfg" /boot/efi/boot/grub.cfg 2>/dev/null
  ok "ROOT-A grub template carries the brightness param"
fi
ok "fixes injected for KVER=$KVER"

# --- Power button: lock + sleep (NOT power-off menu) ---
# 1) board_specific + top-level powerd pref
printf '0\n' > "$W/legacy_power_button"
guestfish --rw -a "$OUT" -m /dev/sda3:/ <<GF 2>/dev/null || true
mkdir-p /usr/share/power_manager/board_specific
upload $W/legacy_power_button /usr/share/power_manager/board_specific/legacy_power_button
upload $W/legacy_power_button /usr/share/power_manager/legacy_power_button
GF
# 2) remove legacy_power_button from ui_use_flags.txt (Ash reads this → power menu)
guestfish --ro -a "$OUT" -m /dev/sda3:/ download /etc/ui_use_flags.txt "$W/ui_use_flags.txt" 2>/dev/null || true
if [ -f "$W/ui_use_flags.txt" ]; then
  grep -v '^legacy_power_button$' "$W/ui_use_flags.txt" > "$W/ui_use_flags.txt.new" || true
  mv "$W/ui_use_flags.txt.new" "$W/ui_use_flags.txt"
  guestfish --rw -a "$OUT" -m /dev/sda3:/ upload "$W/ui_use_flags.txt" /etc/ui_use_flags.txt 2>/dev/null || true
  ok "ui_use_flags: stripped legacy_power_button (power btn → lock/sleep)"
fi
# 3) chrome_dev.conf: explicitly clear legacy power button if present
guestfish --ro -a "$OUT" -m /dev/sda3:/ download /etc/chrome_dev.conf "$W/chrome_dev.conf" 2>/dev/null || true
if [ -f "$W/chrome_dev.conf" ]; then
  if ! grep -q '^!--aura-legacy-power-button' "$W/chrome_dev.conf"; then
    printf '\n# StarLite: power button locks + sleeps display (no power menu)\n!--aura-legacy-power-button\n' >> "$W/chrome_dev.conf"
    guestfish --rw -a "$OUT" -m /dev/sda3:/ upload "$W/chrome_dev.conf" /etc/chrome_dev.conf 2>/dev/null || true
    ok "chrome_dev.conf: !--aura-legacy-power-button"
  fi
fi


if [ "$LEAN" -eq 1 ]; then
  lean_strip_fyde_extras "$OUT"
fi
starlite_refresh_hwdb "$OUT"

say "5) RE-SEAL verity and propagate the NEW digest to ALL FOUR copies"
dd if="$OUT" of="$W/roota2.img" bs=512 skip="$ROOTA_START" count="$PAY_SECTORS" status=none
NEW=$("$TOOLS/run_verity.sh" mode=create alg=sha256 payload="$W/roota2.img" \
      payload_blocks="$PAY_BLOCKS" hashtree="$W/htree.img" salt="$SALT" 2>/dev/null \
      | grep -o 'root_hexdigest=[0-9a-f]*' | cut -d= -f2)
[ -n "$NEW" ] || die "verity re-seal produced no digest"
ok "new digest ${NEW:0:16}…"
# 5a. hashtree goes immediately after the payload, inside ROOT-A
dd if="$W/htree.img" of="$OUT" bs=512 seek=$((ROOTA_START + PAY_SECTORS)) conv=notrunc,fsync status=none
ok "hashtree written at sector $((ROOTA_START + PAY_SECTORS))"
# 5b. ESP grub.cfg — ONLY the A entry. Leave 'verified image B' alone.
python3 - "$W/grub.cfg" "$OLD" "$NEW" <<'PY'
import sys
p,old,new=sys.argv[1:4]; s=open(p).read(); out=[];changed=0
for line in s.splitlines(True):
    if old in line and 'vmlinuz.A' in line:
        line=line.replace(old,new); changed+=1
    if 'i915.enable_psr=0' in line and 'enable_dpcd_backlight' not in line:
        line=line.replace('i915.enable_psr=0','i915.enable_psr=0 i915.enable_dpcd_backlight=0')
    out.append(line)
open(p,'w').write(''.join(out)); print(f"    grub A-entry digest updated: {changed}")
PY
guestfish --rw -a "$OUT" -m /dev/sda12:/ upload "$W/grub.cfg" /efi/boot/grub.cfg 2>/dev/null
# 5c. ESP /syslinux/usb.A.cfg — the A-slot copy everyone forgets
if guestfish --ro -a "$OUT" -m /dev/sda12:/ exists /syslinux/usb.A.cfg 2>/dev/null | grep -q true; then
  guestfish --rw -a "$OUT" -m /dev/sda12:/ download /syslinux/usb.A.cfg "$W/usb.A.cfg" 2>/dev/null
  sed -i "s/$OLD/$NEW/g" "$W/usb.A.cfg"
  grep -q 'enable_dpcd_backlight=0' "$W/usb.A.cfg" || \
    sed -i 's/i915.enable_psr=0/i915.enable_psr=0 i915.enable_dpcd_backlight=0/g' "$W/usb.A.cfg"
  ensure_tpm_hide_cmdline "$W/usb.A.cfg"
  ensure_tpm_hide_cmdline "$W/tmpl.cfg" 2>/dev/null || true
  guestfish --rw -a "$OUT" -m /dev/sda12:/ upload "$W/usb.A.cfg" /syslinux/usb.A.cfg 2>/dev/null
  ok "usb.A.cfg updated"
fi
# 5d. BOTH kernel slots. Devkeys are safe: this is a UEFI machine (grub boots
#     /syslinux/vmlinuz.A), the kernel partition is never used to boot, and
#     chromeos-postinst performs no signature verification.
for slot in A B; do
  if [ "$slot" = A ]; then ST=$KA_START; SZ=$KA_SIZE; else ST=$KB_START; SZ=$KB_SIZE; fi
  dd if="$OUT" of="$W/k$slot.bin" bs=512 skip="$ST" count="$SZ" status=none
  "$TOOLS/run_futility.sh" vbutil_kernel --verify "$W/k$slot.bin" --verbose 2>/dev/null \
    | sed -n '/Config:/,$p' | tail -n +2 > "$W/cfg$slot.txt"
  [ -s "$W/cfg$slot.txt" ] || die "could not read KERN-$slot config"
  sed -i "s/$OLD/$NEW/g" "$W/cfg$slot.txt"
  grep -q 'i915.enable_dpcd_backlight=0' "$W/cfg$slot.txt" || \
    sed -i 's/i915.enable_psr=0/i915.enable_psr=0 i915.enable_dpcd_backlight=0/' "$W/cfg$slot.txt"
  "$TOOLS/run_futility.sh" vbutil_kernel --repack "$W/k$slot.new" \
      --keyblock "$DEVKEYS/kernel.keyblock" \
      --signprivate "$DEVKEYS/kernel_data_key.vbprivk" \
      --oldblob "$W/k$slot.bin" --config "$W/cfg$slot.txt" --version 1 >/dev/null 2>&1 \
      || die "repack of KERN-$slot failed"
  dd if=/dev/zero of="$OUT" bs=512 seek="$ST" count="$SZ" conv=notrunc status=none
  dd if="$W/k$slot.new" of="$OUT" bs=512 seek="$ST" conv=notrunc,fsync status=none
  ok "KERN-$slot repacked + written"
done
sync

say "6) VERIFY"
FAIL=0
# 6a. hashtree on disk matches what we generated
dd if="$OUT" of="$W/ht.chk" bs=512 skip=$((ROOTA_START + PAY_SECTORS)) \
   count=$(( $(stat -c%s "$W/htree.img") / 512 )) status=none
cmp -s "$W/ht.chk" "$W/htree.img" && ok "hashtree on disk matches" || { echo "  ✗ hashtree mismatch"; FAIL=1; }
# 6b. ROOT-A re-hashes to NEW
dd if="$OUT" of="$W/chk.img" bs=512 skip="$ROOTA_START" count="$PAY_SECTORS" status=none
RE=$("$TOOLS/run_verity.sh" mode=create alg=sha256 payload="$W/chk.img" \
     payload_blocks="$PAY_BLOCKS" hashtree="$W/h2.img" salt="$SALT" 2>/dev/null \
     | grep -o 'root_hexdigest=[0-9a-f]*' | cut -d= -f2)
[ "$RE" = "$NEW" ] && ok "ROOT-A re-hashes to the new digest" || { echo "  ✗ ROOT-A digest drift"; FAIL=1; }
# 6c. all four copies agree
for slot in A B; do
  if [ "$slot" = A ]; then ST=$KA_START; SZ=$KA_SIZE; else ST=$KB_START; SZ=$KB_SIZE; fi
  dd if="$OUT" of="$W/rb.bin" bs=512 skip="$ST" count="$SZ" status=none
  D=$("$TOOLS/run_futility.sh" vbutil_kernel --verify "$W/rb.bin" --verbose 2>/dev/null \
      | grep -o 'root_hexdigest=[0-9a-f]*' | cut -d= -f2)
  [ "$D" = "$NEW" ] && ok "KERN-$slot digest correct" || { echo "  ✗ KERN-$slot = ${D:0:16}"; FAIL=1; }
done
G=$(guestfish --ro -a "$OUT" -m /dev/sda12:/ cat /efi/boot/grub.cfg 2>/dev/null | grep -c "$NEW")
[ "$G" -ge 1 ] && ok "grub A entry carries the new digest" || { echo "  ✗ grub not updated"; FAIL=1; }
# 6d. nothing regressed — paths use detected KVER
REQUIRED_PATHS=(
  /usr/sbin/power-sleep /usr/sbin/power-sleep.sh /usr/sbin/edp-resume-fix.sh /usr/sbin/tablet-switch
  /usr/sbin/lid-touch-guard.sh /usr/sbin/external-only-guard.sh
  /usr/sbin/install-to-internal
  /etc/init/power-sleep.conf /etc/init/edp-resume.conf
  /etc/init/tablet-switch.conf /etc/init/lid-touch-guard.conf
  /etc/init/external-only-guard.conf /etc/init/load-mxc4005.conf
  /etc/udev/hwdb.d/61-starlite-accel.hwdb
  /etc/udev/rules.d/61-starlite-accel.rules
  /etc/init/starlite-bt-bluez.conf
  /usr/sbin/wifi-resume-fix.sh /etc/init/wifi-resume.conf /usr/sbin/elastos-wifi-heal
  /etc/init/trunksd.conf /etc/init/tpm2-simulator.conf /etc/init/hwsec-coherence-guard.conf
  /usr/sbin/check_tpm_preinit_condition
  /etc/modules-load.d/starlite-mxc4005.conf
  /usr/bin/crosvm
)
if [ "${MXC_SKIP:-0}" != "1" ]; then
  REQUIRED_PATHS+=(/lib/modules/"$KVER"/kernel/drivers/iio/accel/mxc4005.ko)
fi
for p in "${REQUIRED_PATHS[@]}"; do
  r=$(guestfish --ro -a "$OUT" -m /dev/sda3:/ exists "$p" 2>/dev/null)
  [ "$r" = true ] || { echo "  ✗ MISSING $p"; FAIL=1; }
done
ok "fixes + Android + crosvm present (KVER=$KVER)"

# 6e. vermagic string inside the injected ko matches KVER
if [ "${MXC_SKIP:-0}" = "1" ]; then
  ok "mxc vermagic check skipped (--skip-mxc)"
else
  guestfish --ro -a "$OUT" -m /dev/sda3:/ \
    download "/lib/modules/$KVER/kernel/drivers/iio/accel/mxc4005.ko" "$W/mxc-check.ko" 2>/dev/null || true
  if [ -s "$W/mxc-check.ko" ]; then
    VM=$(starlite_ko_vermagic "$W/mxc-check.ko")
    [ "$VM" = "$KVER" ] && ok "injected mxc4005 vermagic=$VM" || { echo "  ✗ vermagic $VM != $KVER"; FAIL=1; }
  else
    echo "  ✗ could not download injected mxc4005.ko for vermagic check"; FAIL=1
  fi
fi

# 6f. lean checks (only when lean on)
if [ "$LEAN" -eq 1 ]; then
  for gone in \
      /usr/share/chromium/extensions/fogdcaodknbhigpklbhepedofamkfbln.json \
      /usr/share/chromium/extensions/hidnajblbifdkmheebalalchohohmaef.json \
      /usr/share/chromium/extensions/mofiofjpikncjaigmdlblhojbnkabako.json \
      /usr/share/remote-help \
      /usr/share/novnc \
      /usr/share/fydeos-ota-checker \
      /usr/share/fydeos-backup; do
    r=$(guestfish --ro -a "$OUT" -m /dev/sda3:/ exists "$gone" 2>/dev/null)
    if [ "$r" = true ]; then
      echo "  WARN: lean target still present: $gone (may have been absent-on-stock already as dir)"
    fi
  done
  # This OpenFyde image keeps Linux under /opt/google/vms.
  # /opt/google/containers is not part of this layout.
  for keep in /opt/google/vms /usr/bin/crosvm; do
    r=$(guestfish --ro -a "$OUT" -m /dev/sda3:/ exists "$keep" 2>/dev/null)
    [ "$r" = true ] || { echo "  ✗ LEAN REGRESSION missing $keep"; FAIL=1; }
  done
  ok "lean keep-set (ARC/crostini) still present"
fi

if sgdisk -v "$OUT" 2>&1 | grep -qi 'no problems'; then
  ok "GPT clean"
else
  echo "  ✗ GPT problem"; FAIL=1
fi

# Power-button policy checks
guestfish --ro -a "$OUT" -m /dev/sda3:/ download /usr/share/power_manager/board_specific/legacy_power_button "$W/lpb.check" 2>/dev/null || true
if [ -f "$W/lpb.check" ] && grep -qx 0 "$W/lpb.check"; then
  ok "legacy_power_button=0 (lock/sleep, not power menu)"
else
  echo "  ✗ legacy_power_button not 0"; FAIL=1
fi
guestfish --ro -a "$OUT" -m /dev/sda3:/ download /etc/ui_use_flags.txt "$W/ui.check" 2>/dev/null || true
if [ -f "$W/ui.check" ] && ! grep -qx legacy_power_button "$W/ui.check"; then
  ok "ui_use_flags has no legacy_power_button"
else
  echo "  ✗ ui_use_flags still lists legacy_power_button"; FAIL=1
fi
if guestfish --ro -a "$OUT" -m /dev/sda3:/ is-file /usr/sbin/power-sleep 2>/dev/null | grep -q true; then
  ok "power-sleep binary present"
else
  echo "  ✗ power-sleep binary missing"; FAIL=1
fi

# Same OpenFyde kernel: hrtimer trigger must already be built in or shipped.
guestfish --ro -a "$OUT" -m /dev/sda3:/ \
  download "/lib/modules/$KVER/modules.builtin" "$W/modules.builtin" 2>/dev/null || true
HR_KO=$(guestfish --ro -a "$OUT" -m /dev/sda3:/ \
  is-file "/lib/modules/$KVER/kernel/drivers/iio/trigger/iio-trig-hrtimer.ko" 2>/dev/null || true)
HR_GZ=$(guestfish --ro -a "$OUT" -m /dev/sda3:/ \
  is-file "/lib/modules/$KVER/kernel/drivers/iio/trigger/iio-trig-hrtimer.ko.gz" 2>/dev/null || true)
if grep -q iio-trig-hrtimer "$W/modules.builtin" 2>/dev/null \
   || [ "$HR_KO" = true ] || [ "$HR_GZ" = true ]; then
  ok "image kernel provides iio-trig-hrtimer"
else
  echo "  ✗ image kernel has no iio-trig-hrtimer; refusing to build a second kernel"; FAIL=1
fi

guestfish --ro -a "$OUT" -m /dev/sda3:/ \
  download /usr/sbin/is_running_from_installer "$W/installer-check" 2>/dev/null || true
if [ -s "$W/installer-check" ] && [ "$(stat -c%s "$W/installer-check")" -gt 4096 ] \
   && [ "$(od -An -t x1 -N 4 "$W/installer-check" | tr -d ' \n')" = "7f454c46" ]; then
  ok "is_running_from_installer remains the original ELF"
else
  echo "  ✗ is_running_from_installer missing or not an ELF"; FAIL=1
fi

guestfish --ro -a "$OUT" -m /dev/sda3:/ download /etc/init/trunksd.conf "$W/trunksd.check" 2>/dev/null || true
if grep -q '^exec trunksd$' "$W/trunksd.check" 2>/dev/null \
   && ! grep -q -- '--simulator' "$W/trunksd.check"; then
  ok "trunksd has no second simulator"
else
  echo "  ✗ trunksd.conf is not the single-TPM hold"; FAIL=1
fi

say "RESULT"
if [ "$FAIL" -eq 0 ]; then
  sha256sum "$OUT" | tee "$OUT.sha256"
  ok "BUILD GOOD -> $OUT (lean=$LEAN KVER=$KVER)"
  echo "  Flash it, boot the USB (force it in the boot menu — the firmware prefers the"
  echo "  internal disk), create a local account, then use the on-screen Install button."
  echo "  Verify by BOOTING the SSD: postinst discards cros_installer's exit status, so"
  echo "  the success dialog is not proof."
else
  die "BUILD FAILED VERIFICATION — do not flash"
fi
