description "StarLite: use BlueZ. Floss crashes on LE_READ_BUFFER_SIZE_V2."
start on starting btmanagerd
task
script
  mkdir -p /var/lib/bluetooth
  printf "%s" bluez > /var/lib/bluetooth/bluetooth-daemon.current
  chown bluetooth:bluetooth /var/lib/bluetooth/bluetooth-daemon.current
  chmod 0640 /var/lib/bluetooth/bluetooth-daemon.current
end script
